logging:
  pattern:
    dateformat: HH:mm:ss:SSS
  level:
    cn.itcast: debug
spring:
  rabbitmq:
    host: 47.107.226.181 # rabbitMQ的ip地址
    port: 5672 # 端口
    username: itcast
    password: itcast142
    virtual-host: /
    listener:
      simple:
        prefetch: 1
        acknowledge-mode: auto #由Spring框架管理
        retry:
          enabled: true # 开启消费者失败重试
          initial-interval: 1000ms # 初始的失败等待时长为1秒
          multiplier: 1 # 失败的等待时长倍数，下次等待时长 = multiplier * last-interval
          max-attempts: 3 # 最大重试次数
          stateless: true # true无状态；false有状态。如果业务中包含事务，这里改为false